### ISSUE TITLE
SSHFS instances orphaned once SSHFS-Win-Manager exits

### ISSUE THREAD

**Issue by billziss-gh** [evsar3/sshfs-win-manager#1]
## Steps to reproduce

1. Add new SSHFS connection.
2. Click on "Connect" icon to connect to server.
3. Click on "Folder" icon to open Explorer and verify that connection is alive.
4. Quit SSHFS-Win-Manager and verify that file system is still running.
6. Restart SSHFS-Win-Manager.
7. Observe that SSHFS-Win-Manager does not detect that file system is already running.
8. It is impossible to reconnect the connection, because the drive is already taken.

## Expected behavior

I would expect that upon restarting SSHFS-Win-Manager it would detect the running instance of the file system.

----

Re: billziss-gh/sshfs-win#158

**Comment by evsar3** [comment]
Actually it should kill all children instance when the Manager is closed.
I think you didn't noticed that when closing the main window of the Manager it actually still running in the System Tray.
The porblem here seems to be allow only one instance of the manager running. Because I think you opened a new instance of it and it don't detected the processes runing
