### ISSUE TITLE
Can't connect to": Error: SSHFS version 3.5.2

### ISSUE THREAD

**Issue by Sergey-Yalovoy** [evsar3/sshfs-win-manager#147]
![image](https://user-images.githubusercontent.com/70907499/164375401-f0745fa1-77c8-4c44-a1ba-e5a29eebd010.png)

**Comment by Angell1993** [comment]
Turns out that I had the exact same issue, if you are on win10/11 run the SSHFS-Win Manager as Windows 8.. -See Photo for more info..
That fixed the issue for me.

just make sure you got the latest versions from here as well..

https://github.com/winfsp/sshfs-win/releases
https://winfsp.dev/rel/

![Screenshot 2022-07-02 020814](https://user-images.githubusercontent.com/76971746/176994204-c2cf4f0c-63c0-44af-9424-cc40c71ae6b0.jpg)
.

**Comment by Bobrokus** [comment]
> Turns out that I had the exact same issue, if you are on win10/11 run the SSHFS-Win Manager as Windows 8.. -See Photo for more info.. That fixed the issue for me.
> 
> just make sure you got the latest versions from here as well..
> 
> [winfsp/sshfs-win/releases](https://github.com/winfsp/sshfs-win/releases) [winfsp/winfsp/releases](https://github.com/winfsp/winfsp/releases)
> 
> ![Screenshot 2022-07-02 020814](https://user-images.githubusercontent.com/76971746/176994204-c2cf4f0c-63c0-44af-9424-cc40c71ae6b0.jpg) .

The issue still persists

**Comment by okunamayanad** [comment]
I was getting the same error, tried enabling the compatability mode thing mentioned above, tried uninstalling and reinstalling both sshfs-win and winfsp but the error persisted.

The thing was I had to give the connection a name. I think the error message is bit misleading and could've been handled in the UI by requiring a name for creating a connection. I think this issue should be reopened.
