### ISSUE TITLE
No error message

### ISSUE THREAD

**Issue by chopin57otu** [evsar3/sshfs-win-manager#18]
Hello,

my connection is not working for some reason. When I click the plug button the button shows some progress and then turn back to disconnected icon. The issue is I don't receive any error message, so I don't know what's wrong.

I'm using private key. I can initiate SSH connection with the same configuration.

**Comment by evsar3** [comment]
Hello,

Are your private key protected by password?

**Comment by chopin57otu** [comment]
> Hello,
> 
> Is your private key protected by password?

No.

BTW error message from SiriKali (might be the same issue):
![image](https://user-images.githubusercontent.com/15608881/82037493-821c9100-96a2-11ea-8fea-ff1568f684d8.png)

**Comment by evsar3** [comment]
Never seen anything like this... for now I hope someone that experienced such scenario give us some feedback on a possible workarround.

**Comment by mhogomchungu** [comment]
When SiriKali main window has focus, press "CTRL+D" to get debug window and try to connect again to see what command SiriKali is invoking and use it on the terminal to see what error is reported when its failing.

In SiriKali, you are getting that because one part of SiriKali keeps reading sshfs-win output(std error and stdout) waiting to see something in it to recognize as error or success but sshfs-win exits without producing the data SiriKali is expecting.

Another part of SiriKali notices the backend is gone and reported what you are seeing.

The problem from SiriKali perspective are either:
1. sshfs-win exists normally without producing expected error messages.
2. sshfs-win is crashing and exists without producing anything.

**Comment by chopin57otu** [comment]
Hello and thank you for your response

SiriKali debug output:
```
...
Backend took 4 seconds to unlock a volume
***************************
Exit Code: 1
Exit Status: 0
-------
StdOut: 
-------
StdError: 
-------------

SiriKali::Error Backend Disappeared For Some Reason (It Probably Crashed).
-------
Command: "C:\Program Files\SSHFS-Win\\bin\sshfs.exe" -f "ubuntu@****" "U:"  -o rw,fsname=sshfs@"ubuntu@****",subtype=sshfs,idmap=user,StrictHostKeyChecking=no,IdentityFile=C:/Users/****/.ssh/****.ppk,volname="ubuntu@****"
-------
```

command line:
```
C:\Program Files\SSHFS-Win\bin>sshfs -f "ubuntu@****" "U:"  -o rw,fsname=sshfs@"ubuntu@****",subtype=sshfs,idmap=user,StrictHostKeyChecking=no,IdentityFile=C:/Users/****/.ssh/****.ppk,volname="ubuntu@****"

C:\Program Files\SSHFS-Win\bin>
```

Shall I move this issue to [sshfs-win](https://github.com/billziss-gh/sshfs-win) ?

**Comment by mhogomchungu** [comment]
Yes, I think you should. On error, sshfs should print the occured error before exiting.

**Comment by mhogomchungu** [comment]
This option may be the source of the problem ```IdentityFile=C:/Users/****/.ssh/****.ppk```.

Is there a space character hidden in those stars?

**Comment by chopin57otu** [comment]
No, my username is in format `C:\Users\john.doe\.ssh`.

**Comment by cblake777** [comment]
I did run into one command line that caused sshfs.exe to return without doing anything.

The command was: 
```
"C:/Program Files/SSHFS-Win/bin\sshfs.exe" -f "cblakemore@-------:" "S:"  -o rw,fsname="dh04",subtype=sshfs,idmap=user,StrictHostKeyChecking=no,IdentityFile="C:/Users/Carl Blakemore/.ssh/id_rsa",volname="cblakemore@node1.foobar.example.com"
```

I didn't think about it at the time because I was focused on making the ssh connection happen.  I went back and played with it a bit more, the issue is `volname`.  When I reduce the number of characters in volname to `cblakemore@node1.foobar.example.`, then sshfs works and complains about the space in the IdentityFile path.

**Comment by mhogomchungu** [comment]
The problem is caused by a bug in winfsp[1] and this a temporary fix is for this line[2] to be changed to make sure volname does not exceed 32 characters.

[1] https://github.com/billziss-gh/winfsp/issues/311
[2] https://github.com/evsar3/sshfs-win-manager/blob/154016e8d456bf5d54d6a45fff86562c4235319b/src/renderer/ProcessHandlerWin.js#L20

**Comment by evsar3** [comment]
Hello @mhogomchungu 

Great work on throbleshooting this!

Thank you.
