### ISSUE TITLE
no connection

### ISSUE THREAD

**Issue by gorgyx** [evsar3/sshfs-win-manager#4]
Hi,
unfortunately I don't get a connection when I use the sshfs-win manager, whereas my drive IS connected when I use "connect network drive" in Windows Explorer with path \\sshfs.r\user@host\path\to\files (OS= windows 10 Education 1809 64-bit german) . After I click the connect button there is a wait/busy circle, and then the input windows again, but no connection. No error message either. I tried rebooting - the same afterwards. I Installed the software for all users and run it as user without admin rights.
I really would like to have it running - for all the new/Corona Home Office users of our institute. Thanks, Georg

**Comment by evsar3** [comment]
Hello @gorgyx 
First of all, I don't recommend the use of this program in a production environment because it's a very yong project (1 week) and need a couple more weeks of testing and reporting in proper tests environments.

But, let's try throbleshooting this issue:
- Verify if the installation directory of SSHFS-Win matches the path in the 'Settings' of the SSHFS-Win Manager (it must match the path to `the sshfs-win.exe` file, usually in `C:\Program Files\SSHFS-Win\bin\sshfs-win.exe`)
- Make sure that you haven't another drive with the letter you trying to mount
- Verify and kill any other instance of the `sshfs-win.exe` and `sshfs.exe` that is running

**Comment by evsar3** [comment]
Hi @gorgyx 

I ran into an issue that might be the same as yours:
The fingerprint of the server I'm trying to connect wasn't into the known_hosts file. To fix that for now, you might need to connect to your server using ssh and accepting the fingerpring sent by it.

Once the fingerprint is added to the known_hosts file you should be good to go.
I'll take a look into the sshfs options to bypass this verification in next versions.

Waiting for your feedback.
Stay good.

**Comment by Fell** [comment]
I ran into the same issue with the known_hosts file, just letting you know. As long as the host is in there, it works.

**Comment by evsar3** [comment]
Thanks @Fell!
Don't forget to share your impressions about the program with us!
Stay good.

**Comment by Fell** [comment]
@evsar3 Looks good, works great and finally fixed the umask issue I had. It's very intuitive, I love it!
I'll let you know when I run into any other problems.
