### ISSUE TITLE
Documentation on how to compile source

### ISSUE THREAD

**Issue by zardini123** [evsar3/sshfs-win-manager#43]
I would like to contribute to this project, but I have no idea how to compile the source.  Having a short description/tutorial on how to compile the source in the README would be greatly appreciated.

For example, being that this is an electron application:  Do I need to install npm?  How do I initialize the packages?  What command do I run to get a binary?

Thank you very much!

**Comment by evsar3** [comment]
Hi,

If you already have Node.js installed in your computer, you already has NPM on it.
To check if you have them installed, try in your console:
`node -v` and `npm -v`

To setup the project follow these steps:
- Fork this project in your account
- Clone the forked project in your computer
- Run `npm install` in the project's folder to install all dependencies (it must take a few minutes)

For coding, I recommend using Visual Studio Code with this plugins:
- Vetur (Vue.js plugin)
- ESlint (linter for JavaScript)

The code style used is [StandardJS](https://standardjs.com/) which is automatically enforced by ESlint.

In order to run the project in development mode, execute:
```
npm run dev
```
Any changes in the source will automatically be reflected in the running instance of the Manager.

To build the application and generate an installer binary, run:
```
npm run build
```

I will be glad to answer any more questions. Hope you enjoy the project.

**Comment by zardini123** [comment]
Wow, thank you!  This is very detailed!  Thank you for for the plugin recommendations as well, along with stating your code style!  This would be great information to include in the README!

**Comment by evsar3** [comment]
I will include a contributing guide in next stable release

**Comment by peteromano** [comment]
Hi @evsar3!

Since it's been 4 years since this last activity on this thread, I'm trying to build, but it would be useful to know the node version.

Looks like you also need python3 installed, fyi. 

Seems to be ok with node 20, but gyp fails with some "rU" issue on npm install. This older version of npm might not track transient dependencies well. Have you run into this issue before?

Maybe need to use newer electron package or something..
