### ISSUE TITLE
Cannot assign local drive letter (D:)

### ISSUE THREAD

**Issue by Gittyperson** [evsar3/sshfs-win-manager#66]
Thanks for the excellent SSHFS-Win Manager - a Happy New Year to you!

Not sure if there's a limitation somewhere on mapping D: as a network drive letter. In case there isn't, here's my issue. I want to assign the network drive as D:

Locally, there's a single SSD split in two partitions (C and D) and an F: DVD drive. I first started SSHFS-Win Manager to try it out and successfully added my connection (G: was used). I then used Disk Management to change D: to E: and restarted the PC. No issues so far.

I'm now trying to either edit my current connection from G to D, or delete it and create a new one with D: as drive letter. In both cases however, the D: letter does not appear as an option. Available letters always start with E: even though D: is not in use any more.

_I'll also note here that letters that are in use (E and F) are still listed, and of course fail to create a connection._

**Comment by evsar3** [comment]
Hello @Gittyperson 

As `D` is commonly used for hard drive, it was striped out.

In order to workaround this, you might quit the SSHFS-Win Manager, edit the `%AppData%\sshfs-win-manager\vuex.json`, find the profile for your connection and manually edit the `mountPoint` property to `D:`. Save, start SSHFS-Win Manager and mount the drive. If you try to edit this connection using the SSHFS-Win Manager, you might have a crashing or something.

I will add the letter D in next release. Thank you for pointing this.

Happy new year! Cheers!
