### ISSUE TITLE
Connection Abort

### ISSUE THREAD

**Issue by wilsonmfg** [evsar3/sshfs-win-manager#8]
I have sshfs-win working via net use, both //sshfs and //sshfs-k work to map a drive.

in sshfs-win-manager I get  "read: software caused connection abort" no matter authentication or path I put in.

on the server the auth.log doesn't even show an attempt.

what might be going wrong?

**Comment by jbaber** [comment]
I have the same issue.

**Comment by evsar3** [comment]
I need steps to reproduce, what you SSH config and any other variable that allows me to replicate the exact same environment in order to debug and find a solution.

I have successfully connected with a lot of platforms, including GCE, AWS and other services.

I guess we must wait until I face (or other one that can make a pull request) the same problem to get it fixed, because asking for your credentials is something that I think it's not gonna happen.

**Comment by wilsonmfg** [comment]
just an unbuntu 18.04 server, win10 desktop.  my keys were created some time ago using the ssh tools that come with the git-scm.com/ windows install, if that matters, but the windows 10 and git install are new clean installs.  installed latest sshfs-win and the password and key method both worked right out of the box.  in sshfs-win-manager I've tried every single option, which there aren't a lot of, and it's always the same error.

**Comment by evsar3** [comment]
I will try to create a VM with these specs and check if I face the issue.

> is there a log or some option I can enable to get more detail?
Unfortunally such feature is not available yet.

**Comment by evsar3** [comment]
Check your firewall, and other security configs and try to connect.
Try connecting from another computer in another network.

**Comment by wilsonmfg** [comment]
tried with firewall off, no change.
installed on my home PC and it does work, firewall on, same server over VPN.
issue with a domain joined win10 pro?  for what it's worth, sirikali gives a similar error.

**Comment by evsar3** [comment]
🚨
> issue with a domain joined win10 pro?

You should mention this since the beginning... I've have read issues in SSHFS-Win repo about problems connecting from computers controlled by a domain.

See:
- https://github.com/billziss-gh/sshfs-win/issues/155#issuecomment-594578969 (also check the comment after this one)

Also, please send the sshfs-win logs to me. The log location is the quote bellow.

> Can you post the output of the file `diag.bat` that can be found under `C:\Program Files (x86)\WinFsp\bin`?

_Originally posted by @billziss-gh in https://github.com/billziss-gh/sshfs-win/issues/155#issuecomment-594478623_

Please come back and report what happens

**Comment by wilsonmfg** [comment]
I had seen that, and I had stripped the permissions and reset ownership before.

did it again and it's working, so it seems windows is resetting it?  I'll report next time I reboot, have some work to do for now...
